version: "3.8"
services:
  app:
    container_name: dependency-container
    image: dependency-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      DATABASE_URL: postgresql://postgres:5432/customer
      DATABASE_USER: postgrespw
      DATABASE_PASSWORD: postgres
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customer